/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.thelinh.gui;

import com.thelinh.controller.Controller;
import com.thelinh.model.Exam;
import com.thelinh.model.ExamSql;
import com.thelinh.model.Result;
import com.thelinh.model.ResultSql;
import com.thelinh.model.Subject;
import com.thelinh.model.SubjectSql;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.ThreadLocalRandom;
import javax.swing.JOptionPane;
/**
 *
 * @author hoangkien
 */
public class UserMain extends javax.swing.JFrame {
    private ArrayList<Subject> subjectList;
    /**
     * Creates new form UserMain
     */
    public UserMain() {
        initComponents();
        subjectList = SubjectSql.getAllSubject();
        for (Subject s: subjectList) {
            this.cbSubject.addItem(s.getSubjectId().trim() + " - " 
                    + s.getSubjectName().trim());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbSubject = new javax.swing.JComboBox<>();
        btnDoExam = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVIewResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Chính");

        btnDoExam.setText("Làm bài thi");
        btnDoExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoExamActionPerformed(evt);
            }
        });

        jLabel1.setText("Làm bài thi: ");

        jLabel2.setText("Kết quả bài thi");

        btnVIewResult.setText("Xem kết quả");
        btnVIewResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVIewResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVIewResult)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbSubject, 0, 279, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDoExam)
                        .addGap(38, 38, 38))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDoExam)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnVIewResult))
                .addContainerGap(186, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoExamActionPerformed
//        if (Controller.signInUser("hk", "1") != null) {
//            System.out.println("Login success");
//        }
        ArrayList<Exam> examList = ExamSql.getAllExamBySubject(
                this.subjectList.get(this.cbSubject.getSelectedIndex()));
        if (examList.size() == 0) {
            JOptionPane.showMessageDialog(this, "Không có đề thi");
            return;
        }
        int ran = ThreadLocalRandom.current().nextInt(0, examList.size());
        
        System.out.println(ran);
        DoExam doExam = new DoExam(this, true);
        doExam.setQuestionList(examList.get(ran).getQuestionList());
        Exam exam = examList.get(ran);
        doExam.setTime(exam.getTime());
        doExam.start();
        doExam.setVisible(true);
        System.out.println("Correct Answer is: " + doExam.getCorrectAnswer());
        float mark = 10 * Math.round(40.0 * doExam.getCorrectAnswer() / examList.get(ran).getQuestionList().size()) / 40.0f;
        System.out.println("Mark: " + mark);
        JOptionPane.showMessageDialog(this, "Điểm của bạn: " + mark);
        Result result = new Result();
        result.setResult(mark);
        result.setExam(exam);
        result.setUser(Controller.getCurrentUser());
        result.setDate(new Date());
        ResultSql.saveResult(result);
    }//GEN-LAST:event_btnDoExamActionPerformed

    private void btnVIewResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVIewResultActionPerformed
        new ViewResult().setVisible(true);
    }//GEN-LAST:event_btnVIewResultActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoExam;
    private javax.swing.JButton btnVIewResult;
    private javax.swing.JComboBox<String> cbSubject;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
